[package]
name = "core"
version = "0.0.0"
edition = "2021"

[lib]
name = "core"
path = "src/lib.rs"

[dependencies]
ed25519-dalek = { version = "2.1.1", features = ["std"] }

[dev-dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
